### ISSUE TITLE
Cannot unpack Row instance

### ISSUE THREAD

**Issue by mdczaplicki** [sqlalchemy/sqlalchemy2-stubs#112]
**Describe the bug**
`mypy` is complaining about unpacking `Row` object, even though it works.

**To Reproduce**

```py
test_table = Table(
    "test_table",
    metadata,
    Column("i", UUID(as_uuid=True), nullable=False, primary_key=True),
    Column("x", UUID(as_uuid=True), index=True),
    Column("y", UUID(as_uuid=True), index=True),
)
query = test_table.select()
async with engine.connect() as connection:
  result = await connection.execute(query)
row = result.fetchone()
if row:
  my_dict = {**row}
```

**Error**

```
Argument after ** must be a mapping, not "Row"
```

**Versions.**
 - OS: Linux Mint 19.3 Cinnamon
 - Python: 3.7.10
 - SQLAlchemy: 1.4.15
 - Database: PostgreSQL
 - DBAPI: asyncpg

**Comment by CaselIT** [comment]
Hi,

That is a legacy behaviour,  in 1.4 Row behaves like a sequence, not a mapping. It should also raise a deprecation warning iirc.
You would use `_mapping` to get a RowMapping object that behaves like a mapping.
See: https://docs.sqlalchemy.org/en/14/core/connections.html?highlight=row#sqlalchemy.engine.Row

Note that this depends a bit on how the engine is created, since without `future=True` you get back LegacyRow objects. That said you seem to be using async, and that uses the `future=True`, so it would always return `Row` objects

I think this works currently because python falls back to using `keys()` and `__getitem__` in that case. But mypy apparently does not like it, so I'm not sure if we can fix this.

Also `result = await engine.execute(query)` does not seem right, if engine is an instance of engine, and not a connection.

**Comment by mdczaplicki** [comment]
Hmm, OK. Then we'll have to refactor.

PS. True, I've changed an example.

**Comment by CaselIT** [comment]
@bryanforbes do you know if there is a way of making mypy accept the `{**row}` form, even if row is not a explicitly a mapping?

**Comment by bryanforbes** [comment]
I'd have to look into it, but off the top of my head I don't know of a way to do it.

**Comment by mdczaplicki** [comment]
Why would you want to mypy to accept this if you consider it a legacy behavior & it's (supposed to be) marked as deprecated?

**Comment by zzzeek** [comment]
> Why would you want to mypy to accept this if you consider it a legacy behavior & it's (supposed to be) marked as deprecated?

well as you noted, mypy says it's an error, yet "it works".    So basically mypy has no way to note patterns that are only deprecated.    it *seems* more appropriate that it would allow it to "work", as the deprecation warning is where developers would note this is deprecated; with mypy saying "no, this is wrong, wont work at all", that misleading and is why you posted the issue in the first place right?

**Comment by mdczaplicki** [comment]
Well, that's true. Now I am biased since I know I should move away from treating `Row` as `Mapping`.

Just a note, there seem to be no deprecation warning in my case. :(

**Comment by zzzeek** [comment]
> Well, that's true. Now I am biased since I know I should move away from treating `Row` as `Mapping`.
> 
> Just a note, there seem to be no deprecation warning in my case. :(

you need to turn on SQLALCHEMY_WARN_20 and also use Python -Walways or equivalent: https://docs.sqlalchemy.org/en/14/changelog/migration_20.html#migration-to-2-0-step-two-turn-on-removedin20warnings
