### ISSUE TITLE
Improve stubs of classes that have some method copied by create_proxy_methods

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy2-stubs#61]
In most cases a type only superclass can avoid repeating the definitions in one or more classes.

Examples: Session|ScopedSession|AsyncSession; Connection|AsyncConnection

**Comment by kasium** [comment]
@CaselIT since I would be happy to see this in the future, I'm open to open a PR for discussion.
Let me try to summarize my current understand with an example:

scoped_session copies a few methods from Session. Therefore we should extract these methods in a super class and use it in both scoped_session and Session?

**Comment by CaselIT** [comment]
Thanks for the interest, @kasium. I've already started working on this locally, I'll try to open a PR shortly.

I'll tag you once I've opened it

**Comment by kasium** [comment]
Oh great. Thanks a lot 😄

**Comment by CaselIT** [comment]
Added #149  @kasium

**Comment by kasium** [comment]
great, thanks
